/**
 * REST client for the chat backend.
 *
 * Transport split (design.md): REST owns queryable/historical state, the
 * WebSocket layer (WP6) owns realtime events. This module is the only place
 * that speaks HTTP; components and TanStack Query hooks call these fetchers.
 *
 * Demo identity binding: `GET /api/users` is public. Every protected endpoint
 * carries the selected user's UUID in the `X-User-Id` header; missing or
 * unknown identities are rejected by the backend with 401.
 */

export interface User {
  /** Server-assigned UUID, serialized as a string. */
  id: string
  displayName: string
}

export interface Conversation {
  id: string
  participants: User[]
}

/** The authoritative message shape (mirrors the backend `MessageDto`). */
export interface Message {
  id: string
  conversationId: string
  senderId: string
  content: string
  /** ISO-8601 instant, generated by the server. */
  createdAt: string
}

/** HTTP failure with the response status attached for UI branching. */
export class ApiError extends Error {
  readonly status: number

  constructor(status: number, message: string) {
    super(message)
    this.name = 'ApiError'
    this.status = status
  }
}

async function readErrorMessage(response: Response): Promise<string> {
  const contentType = response.headers.get('content-type') ?? ''
  if (contentType.includes('application/json')) {
    const body: unknown = await response.json().catch(() => undefined)
    if (
      typeof body === 'object' &&
      body !== null &&
      'message' in body &&
      typeof (body as { message: unknown }).message === 'string'
    ) {
      return (body as { message: string }).message
    }
  }
  return `${response.status} ${response.statusText}`.trim()
}

/**
 * Performs a JSON request. `userId`, when provided, is sent as `X-User-Id`,
 * which is how the backend binds the window-scoped demo identity on
 * protected endpoints.
 */
async function request<T>(path: string, userId?: string): Promise<T> {
  const headers = new Headers({ Accept: 'application/json' })
  if (userId !== undefined) {
    headers.set('X-User-Id', userId)
  }

  let response: Response
  try {
    response = await fetch(path, { headers })
  } catch {
    throw new ApiError(0, 'Could not reach the server — is the backend running?')
  }

  if (!response.ok) {
    throw new ApiError(response.status, await readErrorMessage(response))
  }
  return (await response.json()) as T
}

/** Public: the fixed set of selectable MVP identities. */
export function fetchUsers(): Promise<User[]> {
  return request<User[]>('/api/users')
}

/** Protected: only conversations in which `userId` participates. */
export function fetchConversations(userId: string): Promise<Conversation[]> {
  return request<Conversation[]>('/api/conversations', userId)
}

/**
 * Protected: message history of a conversation, in deterministic
 * chronological order; non-participants are rejected by the backend.
 */
export function fetchMessages(userId: string, conversationId: string): Promise<Message[]> {
  return request<Message[]>(`/api/conversations/${encodeURIComponent(conversationId)}/messages`, userId)
}
